In [3]:
from pathlib import Path
import pandas as pd
import sys

sys.path.append(str(Path("../src").resolve()))

from config import RAW_ROOT, GROUP4_PATIENTS, BAD_FILES, CHANNEL_ORDER
from utils import load_raw_edf, prepare_raw

print("Checking Group 4 patients...")
print("Group 4 patients:", GROUP4_PATIENTS)

print("Checking Group 4 patients...")
print("Group 4 patients:", GROUP4_PATIENTS)

group4_file_rows = []

for patient_name in GROUP4_PATIENTS:
    patient_folder = RAW_ROOT / patient_name
    edf_files = sorted(patient_folder.glob("*.edf"))
    patient_bad_files = BAD_FILES.get(patient_name, [])

    print("\n" + "=" * 80)
    print(f"Patient: {patient_name}")
    print(f"Total EDF files found: {len(edf_files)}")
    print(f"Known bad files from config: {patient_bad_files}")

    for file_path in edf_files:
        file_name = file_path.name

        raw = load_raw_edf(file_path)
        raw = prepare_raw(raw)

        group4_file_rows.append({
            "patient_name": patient_name,
            "file_name": file_name,
            "n_eeg_channels": len(raw.ch_names),
            "channels": ", ".join(raw.ch_names),
            "is_known_bad": file_name in patient_bad_files
        })

df_group4_files = pd.DataFrame(group4_file_rows)
display(df_group4_files[["patient_name", "file_name", "n_eeg_channels", "is_known_bad"]])

Checking Group 4 patients...
Group 4 patients: ['chb11', 'chb12', 'chb13', 'chb15', 'chb18', 'chb19']
Checking Group 4 patients...
Group 4 patients: ['chb11', 'chb12', 'chb13', 'chb15', 'chb18', 'chb19']

================================================================================
Patient: chb11
Total EDF files found: 35
Known bad files from config: []

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

================================================================================
Patient: chb12
Total EDF files found: 24
Known bad files from config: []

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

================================================================================
Patient: chb13
Total EDF files found: 33
Known bad files from config: []

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

================================================================================
Patient: chb15
Total EDF files found: 40
Known bad files from config: []

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

================================================================================
Patient: chb18
Total EDF files found: 36
Known bad files from config: []

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

================================================================================
Patient: chb19
Total EDF files found: 30
Known bad files from config: []

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

    patient_name     file_name  n_eeg_channels  is_known_bad
0          chb11  chb11_01.edf              23         False
1          chb11  chb11_02.edf              28         False
2          chb11  chb11_03.edf              28         False
3          chb11  chb11_04.edf              28         False
4          chb11  chb11_05.edf              28         False
..           ...           ...             ...           ...
193        chb19  chb19_26.edf              28         False
194        chb19  chb19_27.edf              28         False
195        chb19  chb19_28.edf              28         False
196        chb19  chb19_29.edf              28         False
197        chb19  chb19_30.edf              28         False

[198 rows x 4 columns]

In [4]:
group4_patient_common = {}
group4_patient_summary_rows = []

for patient_name in GROUP4_PATIENTS:
    patient_folder = RAW_ROOT / patient_name
    edf_files = sorted(patient_folder.glob("*.edf"))
    patient_bad_files = set(BAD_FILES.get(patient_name, []))

    valid_files = [f for f in edf_files if f.name not in patient_bad_files]

    print("\n" + "=" * 80)
    print(f"Patient: {patient_name}")
    print(f"Valid files used for common-channel check: {len(valid_files)}")

    if len(valid_files) == 0:
        print("No valid files found after skipping known bad files.")
        group4_patient_common[patient_name] = set()
        continue

    patient_common = None

    for file_path in valid_files:
        raw = load_raw_edf(file_path)
        raw = prepare_raw(raw)
        current_channels = set(raw.ch_names)

        if patient_common is None:
            patient_common = current_channels
        else:
            patient_common = patient_common.intersection(current_channels)

    group4_patient_common[patient_name] = patient_common

    print(f"Common channels inside {patient_name}: {len(patient_common)}")
    print(sorted(patient_common))

    group4_patient_summary_rows.append({
        "patient_name": patient_name,
        "n_valid_files": len(valid_files),
        "n_common_channels_within_patient": len(patient_common),
        "common_channels_within_patient": ", ".join(sorted(patient_common))
    })

df_group4_patient_summary = pd.DataFrame(group4_patient_summary_rows)
display(df_group4_patient_summary)

================================================================================
Patient: chb11
Valid files used for common-channel check: 35

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

Common channels inside chb11: 23
['C3-P3', 'C4-P4', 'CZ-PZ', 'F3-C3', 'F4-C4', 'F7-T7', 'F8-T8', 'FP1-F3', 'FP1-F7', 'FP2-F4', 'FP2-F8', 'FT10-T8', 'FT9-FT10', 'FZ-CZ', 'P3-O1', 'P4-O2', 'P7-O1', 'P7-T7', 'P8-O2', 'T7-FT9', 'T7-P7', 'T8-P8-0', 'T8-P8-1']

================================================================================
Patient: chb12
Valid files used for common-channel check: 24

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

Common channels inside chb12: 4
['--0', '--1', '--2', '--3']

================================================================================
Patient: chb13
Valid files used for common-channel check: 33

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

Common channels inside chb13: 21
['--0', '--1', '--2', '--3', 'C3-P3', 'C4-P4', 'CZ-PZ', 'F3-C3', 'F4-C4', 'F7-T7', 'F8-T8', 'FP1-F3', 'FP1-F7', 'FP2-F4', 'FP2-F8', 'FZ-CZ', 'P3-O1', 'P4-O2', 'P7-O1', 'P8-O2', 'T7-P7']

================================================================================
Patient: chb15
Valid files used for common-channel check: 40

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4, --5
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

Common channels inside chb15: 30
['--0', '--1', '--2', '--3', '--4', 'C3-P3', 'C4-P4', 'CP1-Ref', 'CP2-Ref', 'CP5-Ref', 'CP6-Ref', 'CZ-PZ', 'F3-C3', 'F4-C4', 'F7-T7', 'F8-T8', 'FC1-Ref', 'FC2-Ref', 'FC5-Ref', 'FC6-Ref', 'FP1-F3', 'FP1-F7', 'FP2-F4', 'FP2-F8', 'FZ-CZ', 'P3-O1', 'P4-O2', 'P7-O1', 'P8-O2', 'T7-P7']

================================================================================
Patient: chb18
Valid files used for common-channel check: 36

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'.', 'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

Common channels inside chb18: 17
['C3-P3', 'C4-P4', 'CZ-PZ', 'F3-C3', 'F4-C4', 'F7-T7', 'F8-T8', 'FP1-F3', 'FP1-F7', 'FP2-F4', 'FP2-F8', 'FZ-CZ', 'P3-O1', 'P4-O2', 'P7-O1', 'P8-O2', 'T7-P7']

================================================================================
Patient: chb19
Valid files used for common-channel check: 30

C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8', '-'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
C:\Users\MSI\Desktop\EEG_FYP\src\utils.py:20: RuntimeWarning: Scaling factor is not defined in following channels:
--0, --1, --2, --3, --4
  raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)

Common channels inside chb19: 21
['--0', '--1', '--2', '--3', 'C3-P3', 'C4-P4', 'CZ-PZ', 'F3-C3', 'F4-C4', 'F7-T7', 'F8-T8', 'FP1-F3', 'FP1-F7', 'FP2-F4', 'FP2-F8', 'FZ-CZ', 'P3-O1', 'P4-O2', 'P7-O1', 'P8-O2', 'T7-P7']

,patient_name,n_valid_files,n_common_channels_within_patient,common_channels_within_patient
0,chb11,35,23,"C3-P3, C4-P4, CZ-PZ, F3-C3, F4-C4, F7-T7, F8-T..."
1,chb12,24,4,"--0, --1, --2, --3"
2,chb13,33,21,"--0, --1, --2, --3, C3-P3, C4-P4, CZ-PZ, F3-C3..."
3,chb15,40,30,"--0, --1, --2, --3, --4, C3-P3, C4-P4, CP1-Ref..."
4,chb18,36,17,"C3-P3, C4-P4, CZ-PZ, F3-C3, F4-C4, F7-T7, F8-T..."
5,chb19,30,21,"--0, --1, --2, --3, C3-P3, C4-P4, CZ-PZ, F3-C3..."

In [5]:
for patient_name, ch_set in group4_patient_common.items():
    print("\n" + "=" * 80)
    print(f"Patient: {patient_name}")
    print(f"Number of common channels: {len(ch_set)}")
    print(sorted(ch_set))

================================================================================
Patient: chb11
Number of common channels: 23
['C3-P3', 'C4-P4', 'CZ-PZ', 'F3-C3', 'F4-C4', 'F7-T7', 'F8-T8', 'FP1-F3', 'FP1-F7', 'FP2-F4', 'FP2-F8', 'FT10-T8', 'FT9-FT10', 'FZ-CZ', 'P3-O1', 'P4-O2', 'P7-O1', 'P7-T7', 'P8-O2', 'T7-FT9', 'T7-P7', 'T8-P8-0', 'T8-P8-1']

================================================================================
Patient: chb12
Number of common channels: 4
['--0', '--1', '--2', '--3']

================================================================================
Patient: chb13
Number of common channels: 21
['--0', '--1', '--2', '--3', 'C3-P3', 'C4-P4', 'CZ-PZ', 'F3-C3', 'F4-C4', 'F7-T7', 'F8-T8', 'FP1-F3', 'FP1-F7', 'FP2-F4', 'FP2-F8', 'FZ-CZ', 'P3-O1', 'P4-O2', 'P7-O1', 'P8-O2', 'T7-P7']

================================================================================
Patient: chb15
Number of common channels: 30
['--0', '--1', '--2', '--3', '--4', 'C3-P3', 'C4-P4', 'CP1-Ref', 'CP2-Ref', 'CP5-Ref', 'CP6-Ref', 'CZ-PZ', 'F3-C3', 'F4-C4', 'F7-T7', 'F8-T8', 'FC1-Ref', 'FC2-Ref', 'FC5-Ref', 'FC6-Ref', 'FP1-F3', 'FP1-F7', 'FP2-F4', 'FP2-F8', 'FZ-CZ', 'P3-O1', 'P4-O2', 'P7-O1', 'P8-O2', 'T7-P7']

================================================================================
Patient: chb18
Number of common channels: 17
['C3-P3', 'C4-P4', 'CZ-PZ', 'F3-C3', 'F4-C4', 'F7-T7', 'F8-T8', 'FP1-F3', 'FP1-F7', 'FP2-F4', 'FP2-F8', 'FZ-CZ', 'P3-O1', 'P4-O2', 'P7-O1', 'P8-O2', 'T7-P7']

================================================================================
Patient: chb19
Number of common channels: 21
['--0', '--1', '--2', '--3', 'C3-P3', 'C4-P4', 'CZ-PZ', 'F3-C3', 'F4-C4', 'F7-T7', 'F8-T8', 'FP1-F3', 'FP1-F7', 'FP2-F4', 'FP2-F8', 'FZ-CZ', 'P3-O1', 'P4-O2', 'P7-O1', 'P8-O2', 'T7-P7']

In [6]:
group4_global_common = None

for patient_name, ch_set in group4_patient_common.items():
    if len(ch_set) == 0:
        continue

    if group4_global_common is None:
        group4_global_common = set(ch_set)
    else:
        group4_global_common = group4_global_common.intersection(ch_set)

if group4_global_common is None:
    group4_global_common = set()

print("\n" + "=" * 80)
print("Possible global common channels across ALL Group 4 patients:")
print(f"Count: {len(group4_global_common)}")
print(sorted(group4_global_common))

================================================================================
Possible global common channels across ALL Group 4 patients:
Count: 0
[]