In [1]:
from pathlib import Path
import pandas as pd
import sys

sys.path.append(str(Path("../src").resolve()))

from config import (
    RAW_ROOT,
    GROUP1_PATIENTS,
    GROUP2_PATIENTS,
    GROUP3_PATIENTS,
    GROUP4_PATIENTS
)

from utils import parse_chbmit_summary

all_patients = (
    GROUP1_PATIENTS +
    GROUP2_PATIENTS +
    GROUP3_PATIENTS +
    GROUP4_PATIENTS
)

seizure_rows = []

for patient_name in all_patients:
    patient_folder = RAW_ROOT / patient_name
    summary_path = patient_folder / f"{patient_name}-summary.txt"

    if not summary_path.exists():
        seizure_rows.append({
            "patient_name": patient_name,
            "n_files_with_seizures": 0,
            "n_total_seizure_intervals": 0,
            "has_seizure": False
        })
        continue

    summary_dict = parse_chbmit_summary(summary_path)

    n_files_with_seizures = 0
    n_total_seizure_intervals = 0

    for file_name, seizure_intervals in summary_dict.items():
        if len(seizure_intervals) > 0:
            n_files_with_seizures += 1
            n_total_seizure_intervals += len(seizure_intervals)

    seizure_rows.append({
        "patient_name": patient_name,
        "n_files_with_seizures": n_files_with_seizures,
        "n_total_seizure_intervals": n_total_seizure_intervals,
        "has_seizure": n_total_seizure_intervals > 0
    })

df_patient_seizure_check = pd.DataFrame(seizure_rows)
display(df_patient_seizure_check.sort_values(["has_seizure", "n_total_seizure_intervals"], ascending=[False, False]))

print("Patients WITH seizures:")
display(df_patient_seizure_check[df_patient_seizure_check["has_seizure"] == True])

print("\nPatients WITHOUT seizures:")
display(df_patient_seizure_check[df_patient_seizure_check["has_seizure"] == False])

   patient_name  n_files_with_seizures  n_total_seizure_intervals  has_seizure
0         chb01                      7                          7         True
1         chb02                      3                          3         True
2         chb03                      0                          0        False
3         chb04                      0                          0        False
4         chb05                      0                          0        False
5         chb06                      0                          0        False
6         chb07                      0                          0        False
7         chb08                      0                          0        False
8         chb09                      0                          0        False
9         chb10                      0                          0        False
10        chb23                      0                          0        False
11        chb24                      0                          0        False
12        chb14                      0                          0        False
13        chb20                      0                          0        False
14        chb21                      0                          0        False
15        chb22                      0                          0        False
16        chb16                      0                          0        False
17        chb17                      0                          0        False
18        chb11                      0                          0        False
19        chb12                      0                          0        False
20        chb13                      0                          0        False
21        chb15                      0                          0        False
22        chb18                      0                          0        False
23        chb19                      0                          0        False

Patients WITH seizures:

  patient_name  n_files_with_seizures  n_total_seizure_intervals  has_seizure
0        chb01                      7                          7         True
1        chb02                      3                          3         True

Patients WITHOUT seizures:

   patient_name  n_files_with_seizures  n_total_seizure_intervals  has_seizure
2         chb03                      0                          0        False
3         chb04                      0                          0        False
4         chb05                      0                          0        False
5         chb06                      0                          0        False
6         chb07                      0                          0        False
7         chb08                      0                          0        False
8         chb09                      0                          0        False
9         chb10                      0                          0        False
10        chb23                      0                          0        False
11        chb24                      0                          0        False
12        chb14                      0                          0        False
13        chb20                      0                          0        False
14        chb21                      0                          0        False
15        chb22                      0                          0        False
16        chb16                      0                          0        False
17        chb17                      0                          0        False
18        chb11                      0                          0        False
19        chb12                      0                          0        False
20        chb13                      0                          0        False
21        chb15                      0                          0        False
22        chb18                      0                          0        False
23        chb19                      0                          0        False